### ISSUE TITLE
my pictures folder chokes the app with a networking error

### ISSUE THREAD

**Issue by cpg** [amahi/ios#41] opened 2018-03-11 09:58 UTC
there appears to be no such error on the call over the network, just the app displays a (rather amateurish-looking "Oops!" error), network error alert. Pulling down does not seem to help.

i can provide the output of my pictures folder (about 578 entries) in private.

**Comment by cpg** [comment] 2018-03-11 10:03
incidentally, but somewhat unrelated, we saw one user this past week that has trouble with movies (in the existing app) because the movies folder has 5400+ entries.

**Comment by csoni111** [comment] 2018-03-11 22:57
I first tried with 500 files in my share, it opens fine. Then I tired with 1000 files in my share and it failed to load the files. This pops up in the logs: 
```
2018-03-12 09:39:00.045526+0530 AmahiAnywhere[5415:175620] HTTP load failing due to strict content length - expected: 106018, received: 0, received (uncompressed): 0

2018-03-12 09:39:00.046011+0530 AmahiAnywhere[5415:175523] Task <A39B71BE-13D7-437C-87FA-3DA17372AB5E>.<15> finished with error - code: -1005

Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x60400084c060 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x604000483bb0 [0x1103babb0]>{length = 16, capacity = 16, bytes = 0x100201bbd073c9c40000000000000000}}}, NSErrorFailingURLStringKey=, NSErrorFailingURLKey=, NSLocalizedDescription=The network connection was lost.}
```

My guess is that the ios app is closing the connection to the server before it receives the complete response. One way to avoid this situation would be to implement pagination for each directory listing on the AA server.

**Comment by cpg** [comment] 2018-03-12 23:00
Yes, though, I am suspecting this has got to do that networking library. The existing iOS app can read my pictures folder *extremely* fast. So fast that it appears local to the phone, even when doing a pull down to refresh.

Now, the existing app has trouble with someone having 2500+ entries, and pagination would help, however, I would like to settle that separately and deal with this issue first because it seems like basic things are performing really bad as it is.

**Comment by codedentwickler** [comment] 2018-03-12 23:11
I agree with @cpg. I think the issue is from Lightbox. Maybe you should try out another library. https://github.com/rs/SDWebImage is widely used. What do you think? @csoni111

**Comment by csoni111** [comment] 2018-03-13 06:03
@codedentwickler This issue has got nothing to do with LightBox. This is happening on ServerFiles screen. Here alamofire is failing the api request to fetch the all the file names in the directory.
The LightBox issue is on #43 .

**Comment by csoni111** [comment] 2018-03-19 11:47
@cpg After doing some tests I finally found that the pfe server is responsible for this. The pfe server fails to give response if the response content goes above 65kb (approx). So the content won't load using `Remote` mode since pfe fails.

To replicate this error: 
- Make an empty folder in any of your hda's share.
- Create multiple 0kb files in the folder using `touch random{001..500}.txt`, this will create 500 files in the folder.
- Fetch the directory listing in remote mode from pfe server. This will succeed.
- Now make 100 files more `touch random{501..600}.txt`.
- Fetch the directory listing again, the pfe server will fail to give response.

In my tests the pfe server failed after 539 files and the highest Content-Length I could get was `65515`.

Since the current app has only `Remote` mode at present, so the app fails to load the content.

**Comment by cpg** [comment] 2018-03-19 13:03
> Since the current app has only Remote mode at present, so the app fails to load the content.

Whoa. I thought it was local only!

**Comment by cpg** [comment] 2018-03-20 05:41
I tried with the local server address to force local access --- the app behaves erratically, albeit much faster.

I have a folder with about 229MB of photos (45 photos) which I happened to try first and it can reliably crash the app.

With the debugger attached, memory use spikes to 550MB very quickly after opening the first image (and not before then, even when the images are cached, since I don't see them being requested in the back-end server), and the debugger disconnects, crashing the app.

A folder with 28MB spikes to 90MB and stabilizes at 70MB. A folder of 144MB actually decreases memory usage from 70MB to 44MB and steadily rising when browsing photos to 200+MB. At some point the app crashes and the debugger disconnects.

So, while we may have a server bug in the proxy, I think the client may not be 100% out of blame.

**Comment by cpg** [comment] 2019-07-03 08:14
Do we know where are we on this?

**Comment by csoni111** [comment] 2019-07-28 19:48
@cpg as far as I remember, the issue with pfe not being able to send content over 65kb (approx) was resolved when we switched from SPDY to HTTP2 on PFE server. Just for being sure, I tested it again locally, and it works perfectly fine. So this issue can be closed now.

**Closed** 2020-07-28 11:11 UTC
